// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-agents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var search_agents_default = defineTool({
  name: "search_agents",
  title: "Search agents",
  description: "Search the AgentDir directory for AI agents by keyword (matches name, tagline, or description). Returns up to 20 agents with slug, name, tagline, provider, ecosystem, rating, GitHub stars, and website.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search keyword, e.g. 'coding' or 'browser'"),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("agents").select("slug,name,tagline,provider,ecosystem,rating,website_url,github_url,trending_score,github_repos(stars)").or(`name.ilike.%${query}%,tagline.ilike.%${query}%,description.ilike.%${query}%`).order("rating", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      slug: r.slug,
      name: r.name,
      tagline: r.tagline,
      provider: r.provider,
      ecosystem: r.ecosystem,
      rating: Number(r.rating) || 0,
      website: r.website_url,
      github: r.github_url,
      githubStars: Array.isArray(r.github_repos) ? r.github_repos[0]?.stars ?? null : r.github_repos?.stars ?? null,
      trendingScore: r.trending_score != null ? Number(r.trending_score) : 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { agents: rows }
    };
  }
});

// src/lib/mcp/tools/get-agent.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_agent_default = defineTool2({
  name: "get_agent",
  title: "Get agent details",
  description: "Fetch full details for one AI agent by slug: description, features, use cases, provider, pricing, GitHub stars, language, license, tags, and links.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Agent slug, e.g. 'autogen' or 'devin'")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("agents").select("*, github_repos(*)").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No agent found with slug '${slug}'` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { agent: data }
    };
  }
});

// src/lib/mcp/tools/list-trending.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
var list_trending_default = defineTool3({
  name: "list_trending_agents",
  title: "List trending agents",
  description: "Return the most trending AI agents on AgentDir this week, ranked by composite trending score (news mentions + weekly GitHub star growth).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 10)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("agents").select("slug,name,tagline,provider,trending_score,news_count,star_delta_weekly,website_url").order("trending_score", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { agents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_categories_default = defineTool4({
  name: "list_categories",
  title: "List categories",
  description: "List all agent type categories (coding, research, browser, automation, etc.) in the AgentDir directory.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("agent_types").select("slug,name,description").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-review.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var create_review_default = defineTool5({
  name: "create_review",
  title: "Create or update a review",
  description: "Post a rating (1-5) and optional text review for an AI agent, as the signed-in user. Updates the existing review if you already reviewed this agent.",
  inputSchema: {
    agent_slug: z4.string().trim().min(1).describe("Slug of the agent to review"),
    rating: z4.number().int().min(1).max(5).describe("Rating from 1 to 5"),
    review_text: z4.string().trim().max(4e3).optional().describe("Optional review text")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ agent_slug, rating, review_text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const db = supabaseForUser(ctx);
    const { data: agent, error: aErr } = await db.from("agents").select("id,slug,name").eq("slug", agent_slug).maybeSingle();
    if (aErr) return { content: [{ type: "text", text: aErr.message }], isError: true };
    if (!agent) return { content: [{ type: "text", text: `No agent found with slug '${agent_slug}'` }], isError: true };
    const userId = ctx.getUserId();
    const { data: existing } = await db.from("agent_reviews").select("id").eq("agent_id", agent.id).eq("user_id", userId).maybeSingle();
    if (existing) {
      const { data: data2, error: error2 } = await db.from("agent_reviews").update({ rating, review_text: review_text ?? null }).eq("id", existing.id).select().single();
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      return {
        content: [{ type: "text", text: `Updated review for ${agent.name} (rating: ${rating}/5).` }],
        structuredContent: { review: data2 }
      };
    }
    const { data, error } = await db.from("agent_reviews").insert({ agent_id: agent.id, user_id: userId, rating, review_text: review_text ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Posted review for ${agent.name} (rating: ${rating}/5).` }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/list-my-reviews.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient6(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_reviews_default = defineTool6({
  name: "list_my_reviews",
  title: "List my reviews",
  description: "List every AgentDir review authored by the signed-in user, with agent name and rating.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const db = supabaseForUser2(ctx);
    const { data, error } = await db.from("agent_reviews").select("id,rating,review_text,created_at,updated_at,agents(slug,name)").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hxoznhqwesgscacnffcp";
var mcp_default = defineMcp({
  name: "agentdir-mcp",
  title: "AgentDir MCP",
  version: "0.1.0",
  instructions: "Tools for AgentDir \u2014 the directory of AI agents. Use `search_agents` and `get_agent` to browse the catalog, `list_trending_agents` for what's hot this week, `list_categories` for taxonomy, and `create_review` / `list_my_reviews` to manage the signed-in user's reviews.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_agents_default, get_agent_default, list_trending_default, list_categories_default, create_review_default, list_my_reviews_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
